// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhQ2wv84AEw-IkZbilBZkRNFZSxFFuYV4',
    appId: '1:645786082884:web:9b4340125d0afcc1c56611',
    messagingSenderId: '645786082884',
    projectId: 'mobiledevicesgroupproject',
    authDomain: 'mobiledevicesgroupproject.firebaseapp.com',
    storageBucket: 'mobiledevicesgroupproject.appspot.com',
    measurementId: 'G-BTMEKNH72W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDKXkJTI7CEsEZV4QYmx_cv14qdl-eeBQ',
    appId: '1:645786082884:android:7778138050f9eaaac56611',
    messagingSenderId: '645786082884',
    projectId: 'mobiledevicesgroupproject',
    storageBucket: 'mobiledevicesgroupproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAdc6ugX_GyjJKoidlhPGPqRQGp0lAl8k',
    appId: '1:645786082884:ios:c460681eb033c5abc56611',
    messagingSenderId: '645786082884',
    projectId: 'mobiledevicesgroupproject',
    storageBucket: 'mobiledevicesgroupproject.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAdc6ugX_GyjJKoidlhPGPqRQGp0lAl8k',
    appId: '1:645786082884:ios:9a049215a9edd466c56611',
    messagingSenderId: '645786082884',
    projectId: 'mobiledevicesgroupproject',
    storageBucket: 'mobiledevicesgroupproject.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
